- name: "installation de wordpress"
  hosts: all
  become: true
  vars_files:
  #  - files/default.yml
    - files/secrets/credentials.yml
  roles:
    - role: php
    - role: mysql
    - role: wordpress
