---
  - name: "Create dir /var/www/html"
    file:
       path: "/var/www/{{ wordpress_host }}"
       state: directory
       owner: apache
       group: apache
       mode: "755"
       
  - name: Téléchargement de la version latest WordPress
    unarchive:
       src: https://wordpress.org/latest.tar.gz
       dest: "/var/www/html"
       remote_src: yes
       owner: apache
       group: apache
       mode: "755"

  - name: Mettre en place Apache VirtualHost
    template:
       src: "virtual_host.j2"
       dest: "/etc/httpd/conf.d/{{ wordpress_host }}"
       owner: root
       group: root
       mode: '0755'
 
  - name: Mettre en place Apache VirtualHost
    template:
       src: "wp-config.php.j2"
       dest: "/var/www/html/wordpress/wp-config.php"
       owner: root
       group: root
       mode: '0755'

  - name: "restart httpd"
    service:
       name: httpd
       state: restarted
       enabled: yes
