---
- name: Install wordpress en Centos 7 machine
  hosts: all
  become: yes
  vars_files:
      - files/secrets/credentials.yml
  vars:
     host: myhostname
     port: 80
     db_name: wordpress
     mysql_user_login: wordpress
     mysql_user_password: wordpress
     db_host: localhost
  tasks:
  - name: "Create dir /var/www/{{host}}"
    file:
       path: "/var/www/{{ host }}"
       state: directory
       owner: apache
       group: apache
       mode: "755"
       
  - name: Téléchargement de la version latest WordPress
    unarchive:
       src: https://wordpress.org/latest.tar.gz
       dest: "/var/www/{{ host }}"
       remote_src: yes
       owner: apache
       group: apache
       mode: "755"

  - name: Mettre en place Apache VirtualHost
    template:
       src: "files/virtual_host.j2"
       dest: "/etc/httpd/conf.d/{{ host }}"
       owner: root
       group: root
       mode: '0755'
 
  - name: Mettre en place Apache VirtualHost
    template:
       src: "files/wp-config.php.j2"
       dest: "/var/www/{{ host }}/wordpress/wp-config.php"
       owner: root
       group: root
       mode: '0755'

  - name: "restart httpd"
    service:
       name: httpd
       state: restarted
       enabled: yes
