    - name: "Create database {{db_name}}"
      mysql_db:
        name: "{{db_name}}"
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        state: present
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci

