---
      - name: "Installation du repo"
        yum:
           name: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
           state: present
      - name: "Import gpg key"
        rpm_key:
            state: present
            key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
      - name: "Install python3-PyMySQL library"
        ansible.builtin.pip:
          name:  PyMySQL
          state: present
