    - name: "Install MySQL Server"
      yum:
        name: mysql-community-server
      register: fresh_install
      when: ansible_os_family == "RedHat"

    - name: "Start MySQL Server"
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Get temporary MySQL root password
      shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      when: fresh_install.changed
      register: mysql_root_temp_password
      #mysql_root_temp_password.stdout

    - name: "Init root password"
      shell: mysql -u root --connect-expired-password --password="{{mysql_root_temp_password.stdout}}" -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{mysql_root_password}}';"
      when: fresh_install.changed

    - name: "Start MySQL Server"
      service:
        name: mysqld
        state: restarted
        enabled: yes

    - name: check if user exists
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_user_login }}"
        state: absent
      register: user_absent


    - name: "Create a new database with name 'wordpress'"
      mysql_db:
        name: "{{db_name}}"
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        state: present
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci
      when: user_absent

    - name: Create MY_DBA user in MySQL and grant privileges
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: "{{ mysql_user_login }} "
        password: "{{ mysql_user_password }}"
        host: 'localhost'
        priv: "{{db_name}}.*:ALL"
