---
    - name: get the rpm or apt package facts
      package_facts:
        manager: "auto"

    - name: "Check if epel-release is absent"
      yum:
         name: epel-release
         state: present
      when:  ansible_facts.packages["epel-release"] is undefined

    - name: "Installation firewalld if not present"
      yum:
         name: firewalld
         state: present
      when:  ansible_facts.packages["firewalld"] is undefined

    - name: "Install the remi repo"
      yum:
         name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
         state: present
      when: ansible_facts.packages["remi-release"] is undefined

    - name: "Import gpg key"
      rpm_key:
         state: present
         key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
      when: ansible_facts.packages["remi-release"] is undefined

    - name: "Start and enable firewalld service"
      service:
         name: firewalld
         enabled: yes
         state: started
