---
    - name: "Install httpd"
      yum:
        name: httpd
        state: present
    - name: "Start httpd"
      service:
        name: httpd
        state: started
        enabled: yes
    - name: "permit traffic in public zone for https service"
      firewalld:
        service: https
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
    - name: "permit traffic in public zone for http service"
      firewalld:
        service: http
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
    - name: "Install php 7.4 and necessary extensions"
      yum:
        name:
          - php
          - php-bz2
          - php-mysql
          - php-curl
          - php-gd
          - php-intl
          - php-common
          - php-mbstring
          - php-xml
        enablerepo: remi-php74
        update_cache: true

    - name: "Restart apache"
      service:
        name: httpd
        state: restarted
